import fs from 'node:fs/promises';
import path from 'node:path';
import type { ImportReport } from '@scooper/core';

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function buildReportMarkdown(report: ImportReport): string {
  const lines = [
    '# KAE Import Report',
    '',
    `**Report ID:** ${report.reportId}`,
    `**Generated:** ${report.generatedAt}`,
    `**Duration:** ${formatDuration(report.durationMs)}`,
    '',
    '## Summary',
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Connector | ${report.connectorName} |`,
    `| Source file | ${report.sourceFile} |`,
    `| Repository | ${report.repositoryPath} |`,
    `| Imported | ${report.imported} |`,
    `| Updated | ${report.updated} |`,
    `| Skipped | ${report.skipped} |`,
    `| Sessions | ${report.sessionsCreated} |`,
    `| Git readiness | ${report.gitReadiness.status} |`,
    '',
  ];

  if (report.snapshotPath) {
    lines.push(`**Snapshot:** \`${report.snapshotPath}\``, '');
  }

  if (report.warnings.length > 0) {
    lines.push('## Warnings', '');
    for (const w of report.warnings) lines.push(`- ${w}`);
    lines.push('');
  }

  if (report.errors.length > 0) {
    lines.push('## Errors', '');
    for (const e of report.errors) lines.push(`- ${e}`);
    lines.push('');
  }

  if (report.sourcesCreated.length > 0) {
    lines.push('## Sources Created', '');
    for (const id of report.sourcesCreated) lines.push(`- ${id}`);
    lines.push('');
  }

  if (report.registriesUpdated.length > 0) {
    lines.push('## Registries Updated', '');
    for (const r of report.registriesUpdated) lines.push(`- ${r}`);
    lines.push('');
  }

  lines.push('## Git Readiness Checks', '');
  for (const check of report.gitReadiness.checks) {
    lines.push(`- ${check.passed ? '✓' : '✗'} **${check.label}** — ${check.message}`);
  }

  lines.push('', '---', '*Generated by KAE — Knowledge Acquisition Engine*');
  return lines.join('\n');
}

/** Writes a professional import report to the repository. */
export async function writeImportReport(
  repositoryPath: string,
  report: ImportReport,
): Promise<string> {
  const reportsDir = path.join(repositoryPath, 'ImportReports');
  await fs.mkdir(reportsDir, { recursive: true });
  const timestamp = report.generatedAt.replace(/[:.]/g, '-');
  const fileName = `import-report-${timestamp}.md`;
  const reportFilePath = path.join(reportsDir, fileName);
  const markdown = buildReportMarkdown({ ...report, reportFilePath });
  await fs.writeFile(reportFilePath, markdown, 'utf8');
  return reportFilePath;
}
