import type { ConversationClassification, ParsedDocument } from '@scooper/core';

function formatTimestamp(ts: unknown): string {
  if (typeof ts !== 'number') return 'Unknown';
  const ms = ts > 1e12 ? ts : ts * 1000;
  return new Date(ms).toISOString();
}

function extractSessionSummary(doc: ParsedDocument): string {
  const content = doc.content.trim();
  if (!content) return 'No extractable conversation content. Flagged for manual review.';

  const userMatch = content.match(/### User\s*\n(?:\*[^*]+\*\s*\n)?([\s\S]*?)(?=\n### |\n## |$)/);
  const assistantMatch = content.match(
    /### Assistant\s*\n(?:\*[^*]+\*\s*\n)?([\s\S]*?)(?=\n### |\n## |$)/,
  );

  const userText = userMatch?.[1]?.trim().slice(0, 400) ?? '';
  const assistantText = assistantMatch?.[1]?.trim().slice(0, 400) ?? '';

  const parts: string[] = [];
  if (userText) parts.push(`**User focus:** ${userText}${userText.length >= 400 ? '…' : ''}`);
  if (assistantText) parts.push(`**Assistant response:** ${assistantText}${assistantText.length >= 400 ? '…' : ''}`);
  return parts.join('\n\n') || content.slice(0, 600);
}

function extractKeyTopics(doc: ParsedDocument, classification: ConversationClassification): string[] {
  const topics = new Set<string>();
  topics.add(classification.inferredProject);
  for (const term of classification.recurringTerms.slice(0, 5)) {
    topics.add(term);
  }
  if (typeof doc.metadata.pastedTranscriptCount === 'number' && doc.metadata.pastedTranscriptCount > 0) {
    topics.add('Pasted source material');
  }
  return [...topics].filter(Boolean);
}

/** Builds an Executive Session Record markdown file. */
export function buildExecutiveSessionMarkdown(
  krcId: string,
  doc: ParsedDocument,
  classification: ConversationClassification,
  sourceRelativePath: string,
): string {
  const title = doc.title.trim() || 'Untitled Conversation';
  const importDate = new Date().toISOString().slice(0, 10);

  const lines = [
    `# Executive Session Record — ${title}`,
    '',
    '## Source ID',
    krcId,
    '',
    '## Session Date',
    formatTimestamp(doc.metadata.createTime),
    '',
    '## Classification',
    `- Primary: ${classification.primaryCategory}`,
    `- Categories: ${classification.categories.join(', ')}`,
    `- Confidence: ${classification.confidence}%`,
    `- Project: ${classification.inferredProject}`,
    `- Uncertain: ${classification.uncertain ? 'Yes — review needed' : 'No'}`,
    '',
    '## Rationale',
    classification.rationale,
    '',
    '## Session Summary',
    extractSessionSummary(doc),
    '',
    '## Key Topics',
    ...extractKeyTopics(doc, classification).map((t) => `- ${t}`),
    '',
    '## Recurring Terms',
    ...(classification.recurringTerms.length > 0
      ? classification.recurringTerms.map((t) => `- ${t}`)
      : ['- None detected']),
    '',
    '## Action / Follow-up',
    classification.uncertain
      ? 'Manual review required. Verify project assignment and capability extraction.'
      : 'Pending detailed capability extraction.',
    '',
    '## Transcript Reference',
    sourceRelativePath,
    '',
    '## Notes',
    `Auto-generated by KAE on ${importDate}.`,
  ];

  return lines.join('\n');
}

/** Builds the executive session filename. */
export function buildExecutiveSessionFilename(krcId: string, doc: ParsedDocument): string {
  const slug = doc.title
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 60) || 'Untitled';
  return `${krcId}_${slug}_SESSION.md`;
}
