import type { ImportReviewEntry } from '@scooper/core';

export interface ImportReviewBatch {
  importDate: string;
  importFileName: string;
  conversationsProcessed: number;
  classified: ImportReviewEntry[];
  uncertain: ImportReviewEntry[];
  skipped: ImportReviewEntry[];
  errors: ImportReviewEntry[];
}

/** Builds markdown content for an import review batch. */
export function buildImportReviewSection(batch: ImportReviewBatch): string {
  const lines = [
    `## Import Batch — ${batch.importDate}`,
    '',
    `- **Source file:** ${batch.importFileName}`,
    `- **Conversations processed:** ${batch.conversationsProcessed}`,
    `- **Classified:** ${batch.classified.length}`,
    `- **Uncertain / review needed:** ${batch.uncertain.length}`,
    `- **Skipped (duplicates):** ${batch.skipped.length}`,
    `- **Errors:** ${batch.errors.length}`,
    '',
  ];

  if (batch.classified.length > 0) {
    lines.push('### Classified', '', buildReviewTable(batch.classified), '');
  }

  if (batch.uncertain.length > 0) {
    lines.push('### Uncertain / Review Needed', '', buildReviewTable(batch.uncertain), '');
  }

  if (batch.skipped.length > 0) {
    lines.push('### Skipped', '', buildReviewTable(batch.skipped), '');
  }

  if (batch.errors.length > 0) {
    lines.push('### Errors', '', buildReviewTable(batch.errors), '');
  }

  lines.push('---', '');
  return lines.join('\n');
}

function buildReviewTable(entries: ImportReviewEntry[]): string {
  const header =
    '| KRC ID | Title | Primary Category | All Categories | Confidence | Status | Notes |';
  const sep = '|---|---|---|---|---|---|---|';
  const rows = entries.map((e) => {
    const notes = [e.notes, e.sourcePath ? `Source: ${e.sourcePath}` : ''].filter(Boolean).join('; ');
    return `| ${e.krcId} | ${escapeCell(e.title)} | ${e.primaryCategory} | ${e.categories.join(', ')} | ${e.confidence}% | ${e.status} | ${escapeCell(notes)} |`;
  });
  return [header, sep, ...rows].join('\n');
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Builds the full IMPORT_REVIEW.md file header for a new file. */
export function buildImportReviewHeader(): string {
  return [
    '# Import Review',
    '',
    'Auto-generated by KAE. Lists conversation classifications, uncertain items, skips, and errors.',
    '',
  ].join('\n');
}
